# SPDX-FileCopyrightText: 2026 yonasBSD
#
# SPDX-License-Identifier: MIT

name: Auto Merge Dependabot

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    # Check if the PR is from dependabot
    if: github.actor == 'dependabot[bot]'  # zizmor: ignore[bot-conditions]
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@21025c705c08248db411dc16f3619e6b5f9ea21a # v2.5.0
        with:
          github-token: "${{ secrets.WORKFLOW_TOKEN }}"

      - name: Enable auto-merge for Dependabot PRs
        run: |
          # Approve the PR first
          gh pr review --approve "$PR_URL"

          # Force the squash commit to use the PR title as the subject.
          # This ensures the commit starts with "build(deps):"
          gh pr merge --squash --auto --subject "$PR_TITLE" "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
